import Head from 'next/head';
import axios from 'axios';
import { useEffect, useState } from 'react';
import Roster from '../types/roster';
import RosterItem from '../components/RosterItem';

export default function Home() {
  const [roster, setRoster] = useState<Array<Roster>>([]);

  const fetchRoster = async () => {
    const fetchedRoster = await axios.get('/api/roster');
    setRoster(fetchedRoster.data);
  };

  const deleteRoster = async (id: number) => {
    setRoster(roster.filter((item) => item.id !== id));
    await axios.delete(`/api/roster/${id}`);
  };

  useEffect(() => {
    fetchRoster();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-3">
          <div></div>
          <div className="mt-5">
            <h1 className="text-center text-3xl font-bold">Pokemon Roster Builder</h1>
            <div className="mt-5 grid grid-cols-[2fr_1fr] gap-4">
              <div>
                <input
                  type="text"
                  name="inputRosterName"
                  id="inputRosterName"
                  className="w-full rounded-md border p-2 text-lg"
                />
              </div>
              <div>
                <button className="h-full w-full rounded-md bg-blue-700 text-white hover:bg-blue-900 active:bg-blue-700">
                  Add
                </button>
              </div>
            </div>
            <div className="mt-5 w-full">
              <h3 className="text-xl font-bold">Your rosters</h3>
              <div className="mt-3 w-full">
                {roster ? (
                  roster.map((item) => (
                    <RosterItem key={item.id} roster={item} handleDelete={deleteRoster} />
                  ))
                ) : (
                  <p>Add a roster</p>
                )}
              </div>
            </div>
          </div>
          <div></div>
        </div>
      </main>
    </>
  );
}
